#%RAML 1.0

title: this is a test

types:
  User: !include http://localhost:8081/publishers/myorg/projects/ramlapitest1/versions/154b3808a0639d3eb8d36432b7ac06fd89337d5d/types/user.raml

/hello:
  get:
    responses:
      200:
        body:
          application/json: User
