#%RAML 1.0

title: this is a test

types:
  User: !include http://localhost:8081/publishers/myorg/projects/ramlapitest1/versions/current/types/user.raml

/hello:
  get:
    responses:
      200:
        body:
          application/json: User
